namespace HapetFrontend.Errors
{
    // Compile Time Error Number
    public enum CTEN
    {
        Teapot                          = 0x0000,

        // project errors up to 0x1000
        FullPathToHapetFileNotFound     = 0x0001,
        ProjectFileCouldNotBeParsed     = 0x0002,
        UnexpectedProjectFileTag        = 0x0003,
        ProjectFileException            = 0x0004,
        NoHapetCommandSpecified         = 0x0005,
        NoHapetProjectPathSpecified     = 0x0006,
        NotFoundHapetCommand            = 0x0007,
        ErrorInferencingProjTag         = 0x0008, // possible compiler error
        TagNotParsedToInt               = 0x0009,
        ValueInvalidForTag              = 0x000A,
        AssemblyNotFound                = 0x000B,
        RefProjectNotFound              = 0x000C,
        NoVersionFileFound              = 0x000D,

        // lexer errors up to 0x2000
        FileForLexerNotFound            = 0x1001,
        UnexpectedEndOfStringLit        = 0x1002,

        // parser errors up to 0x3000
        UnexpectedDeclInStruct          = 0x2001,
        ExprsExpectedInBinExpr          = 0x2002,
        ExprsExpectedInBinExprR         = 0x201E,
        ExprExpectedInUnExpr            = 0x2003,
        ArgumentNameNotIdent            = 0x2004,
        FailedToParseArguments          = 0x2005,
        ParameterNameNotIdent           = 0x2006,
        ParamDefaultNotExpr             = 0x2007,
        FailedToParseParameters         = 0x2008,
        LambdaParamNameNotIdent         = 0x2009,
        CastSubNotExpr                  = 0x200A,
        CastTargetNotExpr               = 0x200B,
        ArraySizeNotExpr                = 0x200C,
        ArraySizeNotSpecified           = 0x200D,
        ArrayNonLastNotSpecified        = 0x200E,
        ArrayUnexpectedToken            = 0x200F,
        ArrayElementNotExpr             = 0x2010,
        ArrayElementsUnexpectedToken    = 0x2011,
        CallTargetExprExpected          = 0x2012,
        CallNameIdentExpected           = 0x2013, // would be obsolete
        ArrayAccUnexpectedToken         = 0x2014,
        ArrayAccNoArgs                  = 0x2015,
        ArrayAccTooManyArgs             = 0x2016, // could be obsolete
        ArrayAccNotExpr                 = 0x2017,
        DeclNameIsNotIdent              = 0x2018,
        TildaUnexpectedExpr             = 0x2019, // would be obsolete
        CommonFailToParse               = 0x201A,
        CommonExpectedToken             = 0x201B,
        CommonUnexpectedToken           = 0x201C,
        CommonUnexpectedInExpr          = 0x201D,
        CommonIdentifierExpected        = 0x201F,
        CommonDotUnexpected             = 0x2020,
        CommonIdentAfterDot             = 0x2021,
        VarIniterExpr                   = 0x2022,
        PureUnexpectedToken             = 0x2023,
        StmtNotAllowedInThis            = 0x2024,
        AttrNameExpected                = 0x2025,
        NewlineExpected                 = 0x2026,
        RightSideVarDeclNotExpr         = 0x2027,
        ClassNameExpected               = 0x2028,
        ClassNameNotIdent               = 0x2029,
        IfStmtCondNotExpr               = 0x202A,
        IfStmtCondExpected              = 0x202B,
        SwitchStmtCondNotExpr           = 0x202C,
        SwitchStmtCondExpected          = 0x202D,
        CaseExpectedToBeStmt            = 0x202E,
        CasesExpectedAfterSwitch        = 0x202F,
        CaseParamExprExpected           = 0x2030,
        CaseParamExpected               = 0x2031,
        ExpectedEqualOrNewline          = 0x2032,
        NoReturnTypeInDelegDecl         = 0x2033,
        NoDelegNameAfterReturnType      = 0x2034,
        DelegNameIsNotIdent             = 0x2035,
        TypeNameNotExpr                 = 0x2036,
        TypeNameUnexpected              = 0x2037,
        TypeNameUnexpectedAfter         = 0x2038,
        NoEnumNameAfterEnumWord         = 0x2039,
        EnumNameNotIdent                = 0x203A,
        ManyInhTypesInEnum              = 0x203B,
        EnumFieldIniNotExpr             = 0x203C,
        ThisDeclNotAllowedInEnum        = 0x203D,
        ForLoopSecondNotExpr            = 0x203E,
        WhileLoopParamNotExpr           = 0x203F,
        WhileLoopNoCondition            = 0x2040,
        NoNamespaceAfterUsing           = 0x2041,
        NoNamespaceAfterNamespace       = 0x2042,
        UnexpectedTokenAfterGet         = 0x2043,
        UnexpectedTokenAfterSet         = 0x2044,
        GetNotBeforeSet                 = 0x2045,
        PropIniNotExpr                  = 0x2046,
        NoGetAndNoSetBody               = 0x2047,
        ExpectedGetBody                 = 0x2048,
        ExpectedSetBody                 = 0x2049,
        ExprExpectedAfterReturn         = 0x204A,
        DeclExpectedAfterTheToken       = 0x204B,
        StructDeclExpectedAfterKey      = 0x204C,
        StructNameNotIdent              = 0x204D,
        TheDeclNotAllowedInStruct       = 0x204E,
        ParamsAfterOverloadOperator     = 0x204F,
        TooManyParamsAfterOvOp          = 0x2050,
        UnexpectedUnOpToOverload        = 0x2051,
        UnexpectedBinOpToOverload       = 0x2052,
        GenericTypeNameExpected         = 0x2053,
        GenericTypeNotFound             = 0x2054,
        PropGenericWithoutBody          = 0x2055,
        DeclExpectedInClassStruct       = 0x2056,
        UnexpectedNestedFunc            = 0x2057,
        CommonStringExpected            = 0x2058,
        UnexpectedDirective             = 0x2059,
        UnexpectedGenericConstrain      = 0x205A,
        UserDefinedError                = 0x205B,
        [Obsolete]
        NonStaticNestedLambda           = 0x205C,
        NewExprExpectedAfterThrow       = 0x205D,
        StringLiteralExpectedInInterp   = 0x205E,
        PatternAsExprExpected           = 0x205F,
        PatternResultAsExprExpected     = 0x2060,
        ExpectedAnyGetOrSet             = 0x2061,

        // post preparer errors up to 0x5000
        EnumCouldNotBeAssigned          = 0x3001,
        RequiredTypeNotEvaluated        = 0x3002,
        ArrayVarSizeAndVals             = 0x3003,
        ArraySizeAndValsDiffer          = 0x3004,
        ArrayTypeAsElement              = 0x3005,
        ClassStaticMemStatic            = 0x3006,
        ClassFuncGetSetName             = 0x3007,
        ClassPropFieldExists            = 0x3008,
        ClassPropsFieldsSame            = 0x3009,
        ClassFuncNameNotAllowed         = 0x300A,
        ClassDtorOnlyOne                = 0x300B,
        ClassStorOnlyOne                = 0x300C,
        StmtExpectedToBeDecl            = 0x300D,
        DeclNotAllowedInNamespace       = 0x300E,
        NamespaceAlreadyContains        = 0x300F,
        EnumTypeNotInt                  = 0x3010,
        FieldAlreadyDefined             = 0x3011,
        DoubleInterfaceCringe           = 0x3012, // would be obsolete
        NoFieldImplementation           = 0x3013,
        EnumIniNotComptime              = 0x3014,
        EnumIniNotNumber                = 0x3015,
        VarVarNoIniter                  = 0x3016,
        VarVoidType                     = 0x3017,
        VarTokenNotAllowed              = 0x3018,
        ConstValueNonComptime           = 0x3019,
        UndefOpForType                  = 0x301A,
        TooManyOpsForType               = 0x301B,
        BinUndefOpForTypes              = 0x301C,
        BinTooManyOpsForTypes           = 0x301D,
        OpUsedWithVoidPtr               = 0x301E,
        CreateInterfOrAbsCls            = 0x301F,
        DeclCouldNotBeAccessed          = 0x3020,
        TypeCouldNotBeInfered           = 0x3021,
        FuncCouldNotBeAccessed          = 0x3022,
        FuncWithNameNotFound            = 0x3023,
        NonStaticFuncFromStatic         = 0x3024,
        FuncNotInfered                  = 0x3025,
        CallNotFuncOrDelegate           = 0x3026,
        ExprNotClassOrStruct            = 0x3027,
        SymbolNotFoundInType            = 0x3028,
        NonStringOrArrayIndexed         = 0x3029,
        EnumFieldAssigned               = 0x302A,
        ExprIsNotBool                   = 0x302B,
        MultipleDefaultCases            = 0x302C,
        NonConstantCaseValue            = 0x302D,
        NotEnoughReturns                = 0x302E,
        EmptyReturnStmt                 = 0x302F,
        WrongAttrArgs                   = 0x3030,
        NonComptimeAttrArg              = 0x3031,
        NonSpecifiedRequired            = 0x3032,
        DefaultValueNotFound            = 0x3033,
        TypeCouldNotBeImplCasted        = 0x3034,
        DelegFuncNameExpected           = 0x3035, // could be obsolete
        ExprExpectedToBeFunc            = 0x3036,
        NoMainFunction                  = 0x3037,
        ArrayIndexNotInt                = 0x3038,
        NotExprInAssignment             = 0x3039,
        EmptyReturnExpected             = 0x303A,
        MethodAlreadyDefined            = 0x303B, // could be obsolete
        DoubleInterfaceCringeMeth       = 0x303C, // would be obsolete
        NoMethodImplementation          = 0x303D,
        FunctionShadowing               = 0x303E, // would be obsolete
        PropertyShadowing               = 0x303F, // would be obsolete
        NoAbsMethodImpl                 = 0x3040,
        NoAbsPropertyImpl               = 0x3041,
        AbsMethodWithBody               = 0x3042,
        AbsPropertyWithBody             = 0x3043,
        DerivedFromSealed               = 0x3044,
        NonInterfaceInhInStruct         = 0x3045,
        CannotDeriveFromStruct          = 0x3046,
        AmbiguousCastOverloads          = 0x3047,
        ShouldGoBeforeSpecialKey        = 0x3048,
        AlreadyDefinedSpecialKey        = 0x3049,
        VarDefaultType                  = 0x304A,
        PropaAlreadyDefined             = 0x304B,
        NoPropaImplementation           = 0x304C,
        ExplicitMethodCall              = 0x304D,
        NestedFuncParentNotFound        = 0x304E,
        NestedTypeParentNotFound        = 0x304F,
        ParentStorNotFound              = 0x3050,
        AmbiguousFunctionCall           = 0x3051,
        FuncCallNotOnType               = 0x3052,
        PointerTypeExpected             = 0x3053,
        AttrNotInhFromAttr              = 0x3054,
        ExprTypeNotEvaluated            = 0x3055,
        StaticPolyField                 = 0x3056,
        AttrNotFound                    = 0x3057,
        DeclIsObsolete                  = 0x3058,
        NotSatisfyConstrain             = 0x3059,
        DuplicateConstrain              = 0x305A,
        OnlyOneOnTheConstrains          = 0x305B,
        StaticLambdaToParams            = 0x305C,
        LambdaCouldNotBeCastedToDel     = 0x305D,
        TypeCouldNotBeExplCasted        = 0x305E,
        TypeOfTernaryNotDeterminated    = 0x305F,
        CtorWithArgTypesNotFound        = 0x3060,
        GotoIsNotInSwitchCase           = 0x3061,
        GotoLabelNotFoundInCases        = 0x3062,
        StackAllocOnly1DArray           = 0x3063,
        StackAllocOnlyStructs           = 0x3064,
        NullableNotStruct               = 0x3065,
        ProblemWithArgumentAmount       = 0x3066,
        ArgAndParamModifiersDiff        = 0x3067,
        ArgumentCouldNotBeCasted        = 0x3068,
        ArgumentAmountIsNotCorrect      = 0x3069,
        ArgumentAmountIsNotCorrectDel   = 0x306A,
        CheckedCastOverflow             = 0x306B,

        // compiler errors up to 0x6000
        DefaultWasNotInfered            = 0x5001,
        UnexpectedOperator              = 0x5002,
        StmtNotImplemented              = 0x5003,
        PtrExprCouldNotBeGenerated      = 0x5004,
        AddrOfExprCouldNotBeGenerated   = 0x5005,
        NestedCouldNotBeGenerated       = 0x5006,
        ArrayAccessNotGenerate          = 0x5007,
        StmtInvalidPreparation          = 0x5008,
        NoDefaultValueForType           = 0x5009,
        NoFieldsInNonTypes              = 0x500A,
        OnlyOneDoubleColonInFunc        = 0x500B,
        CouldNotGenerateTypeInfo        = 0x500C,
        CouldNotGenerateVTable          = 0x500D,
        VirtualMethodNotFound           = 0x500E,
        NullProgramFileInMeta           = 0x500F,

        // backend errors up to 0x8000
        TypeCouldNotBeConverted         = 0x6001,
        LLVMValidateError               = 0x6002,
        NoObjectFileGenerated           = 0x6003,
        TheTypeIsNotCallable            = 0x6005,

        NonStaticFieldAccess            = 0x6007, 

        NoLoopToBreak                   = 0x600A,
        NoLoopToContinue                = 0x600B,

        ExternFuncNoAttr                = 0x600D,

        PackLessThanOne                 = 0x600F,
        PackNotPowerOfTwo               = 0x6010,

        // linker errors up to 0x9000
        NoVisualStudio                  = 0x8001, // could be obsolete
        NoVisualStudioHost              = 0x8002, // could be obsolete
        NoVisualStudioLinker            = 0x8003, // could be obsolete
        LinkerItselfError               = 0x8004,
        FailedToLink                    = 0x8005,
        NoWindowsSdk                    = 0x8006, // could be obsolete
        NoVisualStudioLib               = 0x8007, // could be obsolete
        RequiredPathNotFoundForLink     = 0x8008, // could be obsolete
        AssemblyToLinkNotFound          = 0x8009,
    }

    // Run Time Error Number
    public enum RTEN
    {
        Teapot = 0x0000,

    }

    // Compile Time Warning Number
    public enum CTWN
    {
        Teapot = 0x0000,

        // project warnings up to 0x1000

        // lexer warnings up to 0x2000

        // parser warnings up to 0x3000
        ArrayEmptyCreation              = 0x2001,
        StmtsWouldBeIgnored             = 0x2002,
        FieldsInInterface               = 0x2003,
        UserDefinedWarning              = 0x2004,

        // post preparer warnings up to 0x5000
        StaticCtorKwsIgnored            = 0x3001,
        EnumHasSameValue                = 0x3002,
        StaticFuncFromObject            = 0x3003,
        StaticFieldFromObject           = 0x3004,
        StructCastWithAs                = 0x3005,
        DeclIsObsolete                  = 0x3006,
    }
}
