<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\HapetFrontend\HapetFrontend.csproj" />
		<ProjectReference Include="..\HapetPostPrepare\HapetPostPrepare.csproj" />
	</ItemGroup>

</Project>
