using HapetFrontend.Ast.Declarations;
using HapetFrontend.Scoping;
using System.Diagnostics;
using System.Xml.Linq;

namespace HapetFrontend.Ast.Expressions
{
    public class AstBinaryExpr : AstExpression
    {
        public string Operator { get; set; }
        public AstExpression Left { get; set; }
        public AstExpression Right { get; set; }

        /// <summary>
        /// Used probably only for 'is' bin op
        /// when 'is not' is presented
        /// </summary>
        public bool IsNot { get; set; }
        /// <summary>
        /// 'true' if the expr was generated by preparing 'is' bin expr
        /// </summary>
        public bool IsFromIsOperator { get; set; }

        public IBinaryOperator ActualOperator { get; set; }

        /// <summary>
        /// Used in LSP
        /// </summary>
        public ILocation OperatorTokenLocation { get; set; }

        /// <summary>
        /// Used in LSP
        /// </summary>
        public ILocation NotTokenLocation { get; set; }

        public override string AAAName => nameof(AstBinaryExpr);

        public AstBinaryExpr(string op, AstExpression lhs, AstExpression rhs, ILocation location = null) : base(location)
        {
            Operator = op;
            Left = lhs;
            Right = rhs;
        }

        public override AstStatement GetDeepCopy()
        {
            var copy = new AstBinaryExpr(
                Operator,
                Left.GetDeepCopy() as AstExpression,
                Right.GetDeepCopy() as AstExpression,
                Location)
            {
                IsSyntheticStatement = IsSyntheticStatement,
                ActualOperator = ActualOperator,
                IsCompileTimeValue = IsCompileTimeValue,
                IsNot = IsNot,
                IsFromIsOperator = IsFromIsOperator,
                OutType = OutType,
                OutValue = OutValue,
                Scope = Scope,
                SourceFile = SourceFile,
                TupleNameList = TupleNameList,
                OperatorTokenLocation = OperatorTokenLocation,
                NotTokenLocation = NotTokenLocation,
            };
            return copy;
        }

        public override void ReplaceChild(AstStatement oldChild, AstStatement newChild)
        {
            if (Left == oldChild)
                Left = newChild as AstExpression;
            else if (Right == oldChild)
                Right = newChild as AstExpression;
        }
    }
}
