<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" />
    <PackageReference Include="GuiLabs.Language.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HapetFrontend\HapetFrontend.csproj" />
    <ProjectReference Include="..\HapetPostPrepare\HapetPostPrepare.csproj" />
    <ProjectReference Include="..\HapetLastPrepare\HapetLastPrepare.csproj" />
    <ProjectReference Include="..\HapetBackend\HapetBackend.csproj" />
  </ItemGroup>

</Project>
