<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HapetCommon\HapetCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
		<PackageReference Include="GuiLabs.Language.Xml" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" />
    </ItemGroup>
</Project>
