<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Errors\CompileTimeErrors.xml" />
        <None Remove="Errors\CompileTimeWarnings.xml" />
        <None Remove="Errors\RunTimeErrors.xml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HapetCommon\HapetCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
		<PackageReference Include="GuiLabs.Language.Xml" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Errors\CompileTimeErrors.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Errors\CompileTimeWarnings.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Errors\RunTimeErrors.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
