name: Build Windows x64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install NSIS and EnVar Plugin
        shell: pwsh
        run: |
          choco install nsis -y
          
          $envarUrl = "https://github.com/Gserei/NSIS-EnVar/releases/download/v0.0.5/EnVar-Plugin.zip"
          $zipPath = "$env:TEMP\EnVar-Plugin.zip"
          Invoke-WebRequest -Uri $envarUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "C:\Program Files (x86)\NSIS" -Force
          
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "C:\Program Files (x86)\NSIS\Bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Build project and hash computer
        shell: pwsh
        run: | 
          cd build-win
          ./build-x64.ps1
          ls -la
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-files-win-x64
          path: ./build-win/
