name: Build Windows x64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install nsis
        uses: repolevedavaj/install-nsis@v1.0.1
        with:
          nsis-version: '3.10'
      - name: Build project and hash computer
        shell: pwsh
        run: | 
          cd build-win
          ./build-x64.ps1
          ls -la
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-files-win-x64
          path: ./build-win/
